name: publish
on: [push]
jobs:
  publish-php-tool-docker-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the image
        run: |
          docker build . --tag ghcr.io/wollbro/php-tool-image:latest
          docker push ghcr.io/wollbro/php-tool-image:latest
